# Demo compose configuration - includes automated mock data generation
# Use this for demonstrations, testing, and evaluation without Google Fit API setup

services:
  fitlog-demo:
    build: ./Dockerfile.pi
    container_name: fitlog-demo
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - TZ=Asia/Tokyo
      - DEMO_MODE=true
    depends_on:
      - influxdb
    networks:
      - fitlog-network
    # Automated mock data generation every hour
    command: |
      sh -c 'echo "🎬 Starting demo mode with automated mock data generation"
             while true; do
               echo "📊 Generating mock data..."
               python -m fitlog.mock_data --days 7
               echo "⏰ Next generation in 1 hour..."
               sleep 3600
             done's

  influxdb:
    image: influxdb:1.8
    container_name: fitlog-influxdb-demo
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb-demo-data:/var/lib/influxdb2
      - influxdb-demo-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=fitlogdemo2024
      - DOCKER_INFLUXDB_INIT_ORG=fitlog
      - DOCKER_INFLUXDB_INIT_BUCKET=health_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=fitlog-demo-token-12345
    networks:
      - fitlog-network

  grafana:
    image: grafana/grafana-oss:latest
    container_name: fitlog-grafana-demo
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-demo-data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=fitlogdemo2024
      - GF_USERS_ALLOW_SIGN_UP=false
      - INFLUXDB_ADMIN_TOKEN=fitlog-demo-token-12345
    depends_on:
      - influxdb
    networks:
      - fitlog-network

networks:
  fitlog-network:
    driver: bridge

volumes:
  influxdb-demo-data:
  influxdb-demo-config:
  grafana-demo-data:
