# Production compose configuration - requires Google Fit API setup
# Use this for actual health data collection from Google Fit

services:
  fitlog:
    build: .
    container_name: fitlog-prod
    restart: unless-stopped
    volumes:
      - ./fitlog/auth:/app/auth
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - TZ=${TIMEZONE:-Asia/Tokyo}
      - PRODUCTION_MODE=true
    depends_on:
      - influxdb
    networks:
      - fitlog-network
    # Manual execution mode by default
    # Uncomment below for automated hourly data collection:
    # command: |
    #   sh -c 'while true; do
    #     echo "📊 Fetching Google Fit data..."
    #     python -m fitlog.fetch --days 1
    #     echo "⏰ Next fetch in 1 hour..."
    #     sleep 3600
    #   done'
    command: tail -f /dev/null

  influxdb:
    image: influxdb:2.7
    container_name: fitlog-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
      - ./influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
    networks:
      - fitlog-network

  grafana:
    image: grafana/grafana:10.2.0
    container_name: fitlog-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-influxdb-datasource
    depends_on:
      - influxdb
    networks:
      - fitlog-network

networks:
  fitlog-network:
    driver: bridge

volumes:
  influxdb-data:
  grafana-data: