apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: fitlog
    user: admin
    secureJsonData:
      token: ${INFLUXDB_ADMIN_TOKEN}
    jsonData:
      version: Flux
      organization: fitlog
      defaultBucket: health_data
      httpMode: POST
    isDefault: true
    editable: true